### ISSUE TITLE
Fix default color

### ISSUE THREAD

**Issue by zappu9x** [vetrio2511/PullToRefresh#1]

**Comment by m-sameer** [comment]
I would like to work on this issue. But before that, just a polite request, can you please provide name or hex code of the default color to be used.

**Comment by zappu9x** [comment]
Hi! @mhdsmr2 . Default color of refreshview is _white_, but almost backgound color is white too. So, i want to change defaut the refreshview color to gray (#9E9E9E). Hope you help! Tks!

**Comment by m-sameer** [comment]
[Here](https://github.com/vetrio2511/PullToRefresh/blob/master/library/src/main/java/com/vetrio/library/RefreshView.java), should I change both the titleColor and progressColor to gray (#9E9E9E)?

**Comment by zappu9x** [comment]
@mhdsmr2 yep. sure!

**Comment by m-sameer** [comment]
I made a PR, merge it.

**Comment by zappu9x** [comment]
@mhdsmr2. Thank for your pull request!
