### ISSUE TITLE
Add support for Android SDK 26

### ISSUE THREAD

**Issue by m-sameer** [vetrio2511/PullToRefresh#6]
Modify Gradle files to support SDK 26.

**Comment by m-sameer** [comment]
@vetrio2511 Review this issue and [PR](https://github.com/vetrio2511/PullToRefresh/pull/5) and merge it.

**Comment by zappu9x** [comment]
@mhdsmr2 Oh, thank you so much! I merged

**Comment by m-sameer** [comment]
You're welcome, friend.
